// <auto-generated />
using System;
using BeautySky.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeautySky.Migrations
{
    [DbContext(typeof(ProjectSwpContext))]
    partial class ProjectSwpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeautySky.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AnswerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Point")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("QuestionID");

                    b.Property<string>("SkinTypeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AnswerId")
                        .HasName("PK__Answer__D4825024495FE978");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answer", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<string>("AuthorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkinType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BlogId")
                        .HasName("PK__Blog__54379E505182B478");

                    b.HasIndex("UserId");

                    b.ToTable("Blog", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.CarePlan", b =>
                {
                    b.Property<int>("CarePlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CarePlanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarePlanId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SkinTypeId")
                        .HasColumnType("int")
                        .HasColumnName("SkinTypeID");

                    b.HasKey("CarePlanId")
                        .HasName("PK__CarePlan__2EB4A29DE80D6819");

                    b.HasIndex("SkinTypeId");

                    b.ToTable("CarePlan", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.CarePlanProduct", b =>
                {
                    b.Property<int>("CarePlanId")
                        .HasColumnType("int")
                        .HasColumnName("CarePlanID");

                    b.Property<int>("StepId")
                        .HasColumnType("int")
                        .HasColumnName("StepID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<string>("ProductName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CarePlanId", "StepId", "ProductId")
                        .HasName("PK__CarePlan__A043ED686435FBAC");

                    b.HasIndex("ProductId");

                    b.HasIndex("StepId");

                    b.ToTable("CarePlanProduct", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.CarePlanStep", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StepID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StepId"));

                    b.Property<int?>("CarePlanId")
                        .HasColumnType("int")
                        .HasColumnName("CarePlanID");

                    b.Property<string>("StepDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("StepId")
                        .HasName("PK__CarePlan__2434333785293410");

                    b.HasIndex("CarePlanId");

                    b.ToTable("CarePlanStep", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__19093A2BE858798C");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ImageURL");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__News__3214EC272F3627A9");

                    b.ToTable("News");
                });

            modelBuilder.Entity("BeautySky.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("FinalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("PromotionID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BAFB8DE81EA");

                    b.HasIndex("PaymentId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BeautySky.Models.OrderProduct", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("OrderId", "ProductId")
                        .HasName("PK__OrderPro__08D097C1390B35B6");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProduct", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("PaymentStatusId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentStatusID");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentTypeID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__9B556A58C8679860");

                    b.HasIndex("PaymentStatusId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentStatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentStatusId"));

                    b.Property<string>("PaymentStatus1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PaymentStatus");

                    b.HasKey("PaymentStatusId")
                        .HasName("PK__PaymentS__34F8AC1F30EEEE99");

                    b.ToTable("PaymentStatus", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentTypeId"));

                    b.Property<string>("PaymentTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PaymentTypeId")
                        .HasName("PK__PaymentT__BA430B1565009CB5");

                    b.ToTable("PaymentType", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ingredient")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SkinTypeId")
                        .HasColumnType("int")
                        .HasColumnName("SkinTypeID");

                    b.HasKey("ProductId")
                        .HasName("PK__Products__B40CC6ED49962F18");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SkinTypeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BeautySky.Models.ProductsImage", b =>
                {
                    b.Property<int>("ProductsImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductsImageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductsImageId"));

                    b.Property<string>("ImageDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.HasKey("ProductsImageId")
                        .HasName("PK__Products__D92CC439A4C6357F");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductsImage", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PromotionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("PromotionId")
                        .HasName("PK__Promotio__52C42F2FB2DC6819");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("BeautySky.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuestionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("QuizId")
                        .HasColumnType("int")
                        .HasColumnName("QuizID");

                    b.HasKey("QuestionId")
                        .HasName("PK__Question__0DC06F8CA93C3D2D");

                    b.HasIndex("QuizId");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuizID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizId"));

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("QuizName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("QuizId")
                        .HasName("PK__Quiz__8B42AE6EEFC2FAAA");

                    b.ToTable("Quiz", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ReviewId")
                        .HasName("PK__Review__74BC79AE27FBA028");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE3A5A038414");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.SkinType", b =>
                {
                    b.Property<int>("SkinTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SkinTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkinTypeId"));

                    b.Property<string>("SkinTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SkinType");

                    b.HasKey("SkinTypeId")
                        .HasName("PK__SkinType__D5D2962BF35E889E");

                    b.ToTable("SkinType", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DateCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC0A25512A");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053489BB3AA7")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BeautySky.Models.UserAnswer", b =>
                {
                    b.Property<int>("UserAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserAnswerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAnswerId"));

                    b.Property<string>("AnswerId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AnswerID");

                    b.Property<string>("QuestionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("QuestionID");

                    b.Property<int?>("SkinTypeId")
                        .HasColumnType("int")
                        .HasColumnName("SkinTypeID");

                    b.Property<int?>("UserQuizId")
                        .HasColumnType("int")
                        .HasColumnName("UserQuizID");

                    b.HasKey("UserAnswerId")
                        .HasName("PK__UserAnsw__47CE235F34CD2DEC");

                    b.HasIndex("SkinTypeId");

                    b.HasIndex("UserQuizId");

                    b.ToTable("UserAnswer", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.UserCarePlan", b =>
                {
                    b.Property<int>("UserCarePlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserCarePlanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserCarePlanId"));

                    b.Property<int?>("CarePlanId")
                        .HasColumnType("int")
                        .HasColumnName("CarePlanID");

                    b.Property<DateTime?>("DateCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("UserCarePlanId")
                        .HasName("PK__UserCare__9E6AF0B65A697F9B");

                    b.HasIndex("CarePlanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCarePlan", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.UserQuiz", b =>
                {
                    b.Property<int>("UserQuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserQuizID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserQuizId"));

                    b.Property<DateTime?>("DateTaken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("QuizId")
                        .HasColumnType("int")
                        .HasColumnName("QuizID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("UserQuizId")
                        .HasName("PK__UserQuiz__20FA63A7C60101B8");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("UserQuiz", (string)null);
                });

            modelBuilder.Entity("BeautySky.Models.Answer", b =>
                {
                    b.HasOne("BeautySky.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK__Answer__Question__46E78A0C");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BeautySky.Models.Blog", b =>
                {
                    b.HasOne("BeautySky.Models.User", null)
                        .WithMany("Blogs")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BeautySky.Models.CarePlan", b =>
                {
                    b.HasOne("BeautySky.Models.SkinType", "SkinType")
                        .WithMany("CarePlans")
                        .HasForeignKey("SkinTypeId")
                        .HasConstraintName("FK__CarePlan__SkinTy__534D60F1");

                    b.Navigation("SkinType");
                });

            modelBuilder.Entity("BeautySky.Models.CarePlanProduct", b =>
                {
                    b.HasOne("BeautySky.Models.CarePlan", "CarePlan")
                        .WithMany("CarePlanProducts")
                        .HasForeignKey("CarePlanId")
                        .IsRequired()
                        .HasConstraintName("FK__CarePlanP__CareP__59063A47");

                    b.HasOne("BeautySky.Models.Product", "Product")
                        .WithMany("CarePlanProducts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__CarePlanP__Produ__5AEE82B9");

                    b.HasOne("BeautySky.Models.CarePlanStep", "Step")
                        .WithMany("CarePlanProducts")
                        .HasForeignKey("StepId")
                        .IsRequired()
                        .HasConstraintName("FK__CarePlanP__StepI__59FA5E80");

                    b.Navigation("CarePlan");

                    b.Navigation("Product");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("BeautySky.Models.CarePlanStep", b =>
                {
                    b.HasOne("BeautySky.Models.CarePlan", "CarePlan")
                        .WithMany("CarePlanSteps")
                        .HasForeignKey("CarePlanId")
                        .HasConstraintName("FK__CarePlanS__CareP__5629CD9C");

                    b.Navigation("CarePlan");
                });

            modelBuilder.Entity("BeautySky.Models.Order", b =>
                {
                    b.HasOne("BeautySky.Models.Payment", "Payment")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK__Orders__PaymentI__31EC6D26");

                    b.HasOne("BeautySky.Models.Promotion", "Promotion")
                        .WithMany("Orders")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK__Orders__Promotio__30F848ED");

                    b.HasOne("BeautySky.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Orders__UserID__300424B4");

                    b.Navigation("Payment");

                    b.Navigation("Promotion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeautySky.Models.OrderProduct", b =>
                {
                    b.HasOne("BeautySky.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderProd__Order__34C8D9D1");

                    b.HasOne("BeautySky.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderProd__Produ__35BCFE0A");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BeautySky.Models.Payment", b =>
                {
                    b.HasOne("BeautySky.Models.PaymentStatus", "PaymentStatus")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentStatusId")
                        .HasConstraintName("FK__Payment__Payment__2C3393D0");

                    b.HasOne("BeautySky.Models.PaymentType", "PaymentType")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentTypeId")
                        .HasConstraintName("FK__Payment__Payment__2B3F6F97");

                    b.HasOne("BeautySky.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Payment__UserID__2A4B4B5E");

                    b.Navigation("PaymentStatus");

                    b.Navigation("PaymentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeautySky.Models.Product", b =>
                {
                    b.HasOne("BeautySky.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Products__Catego__1BFD2C07");

                    b.HasOne("BeautySky.Models.SkinType", "SkinType")
                        .WithMany("Products")
                        .HasForeignKey("SkinTypeId")
                        .HasConstraintName("FK__Products__SkinTy__1CF15040");

                    b.Navigation("Category");

                    b.Navigation("SkinType");
                });

            modelBuilder.Entity("BeautySky.Models.ProductsImage", b =>
                {
                    b.HasOne("BeautySky.Models.Product", "Product")
                        .WithMany("ProductsImages")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__ProductsI__Produ__1FCDBCEB");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BeautySky.Models.Question", b =>
                {
                    b.HasOne("BeautySky.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .HasConstraintName("FK__Question__QuizID__4316F928");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("BeautySky.Models.Review", b =>
                {
                    b.HasOne("BeautySky.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Review__ProductI__3C69FB99");

                    b.HasOne("BeautySky.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Review__UserID__3D5E1FD2");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeautySky.Models.User", b =>
                {
                    b.HasOne("BeautySky.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__RoleID__15502E78");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BeautySky.Models.UserAnswer", b =>
                {
                    b.HasOne("BeautySky.Models.SkinType", "SkinType")
                        .WithMany("UserAnswers")
                        .HasForeignKey("SkinTypeId")
                        .HasConstraintName("FK__UserAnswe__SkinT__14270015");

                    b.HasOne("BeautySky.Models.UserQuiz", "UserQuiz")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserQuizId")
                        .HasConstraintName("FK__UserAnswe__UserQ__4E88ABD4");

                    b.Navigation("SkinType");

                    b.Navigation("UserQuiz");
                });

            modelBuilder.Entity("BeautySky.Models.UserCarePlan", b =>
                {
                    b.HasOne("BeautySky.Models.CarePlan", "CarePlan")
                        .WithMany("UserCarePlans")
                        .HasForeignKey("CarePlanId")
                        .HasConstraintName("FK__UserCareP__CareP__5FB337D6");

                    b.HasOne("BeautySky.Models.User", "User")
                        .WithMany("UserCarePlans")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__UserCareP__UserI__5EBF139D");

                    b.Navigation("CarePlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeautySky.Models.UserQuiz", b =>
                {
                    b.HasOne("BeautySky.Models.Quiz", "Quiz")
                        .WithMany("UserQuizzes")
                        .HasForeignKey("QuizId")
                        .HasConstraintName("FK__UserQuiz__QuizID__4BAC3F29");

                    b.HasOne("BeautySky.Models.User", "User")
                        .WithMany("UserQuizzes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__UserQuiz__UserID__4AB81AF0");

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeautySky.Models.CarePlan", b =>
                {
                    b.Navigation("CarePlanProducts");

                    b.Navigation("CarePlanSteps");

                    b.Navigation("UserCarePlans");
                });

            modelBuilder.Entity("BeautySky.Models.CarePlanStep", b =>
                {
                    b.Navigation("CarePlanProducts");
                });

            modelBuilder.Entity("BeautySky.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BeautySky.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("BeautySky.Models.Payment", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BeautySky.Models.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BeautySky.Models.PaymentType", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BeautySky.Models.Product", b =>
                {
                    b.Navigation("CarePlanProducts");

                    b.Navigation("OrderProducts");

                    b.Navigation("ProductsImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BeautySky.Models.Promotion", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BeautySky.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("BeautySky.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("UserQuizzes");
                });

            modelBuilder.Entity("BeautySky.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BeautySky.Models.SkinType", b =>
                {
                    b.Navigation("CarePlans");

                    b.Navigation("Products");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("BeautySky.Models.User", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");

                    b.Navigation("UserCarePlans");

                    b.Navigation("UserQuizzes");
                });

            modelBuilder.Entity("BeautySky.Models.UserQuiz", b =>
                {
                    b.Navigation("UserAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
